name: Flutter CI

# This workflow is triggered on pushes to the repository
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  code-analysis-and-testing:
    name: Code Analysis and Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        run: echo "This repository has been cloned to the runner"

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Get pub dependencies
        run: flutter pub get

      - name: Flutter analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test

  build_ios:
    name: Build Flutter (iOS)
    needs: [code-analysis-and-testing] # requires the code-analysis-and-testing to run before the steps run
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Get pub dependencies
        run: flutter pub get

      - name: Flutter clean
        run: flutter clean

      - name: Flutter build ios
        run: flutter build ios --no-codesign

  build_appbundle:
    name: Build Flutter (Android)
    needs: [code-analysis-and-testing] # requires the code-analysis-and-testing to run before the steps run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Get pub dependencies
        run: flutter pub get

      - name: Flutter clean
        run: flutter clean

      - name: Flutter build android
        run: flutter build appbundle
