name: New Flutter CI/CD
on:
  push:
    branches:
      - main

jobs:
  code-analysis-and-testing-with-coverage-analysis:
    name: Code Analysis and Testing With Coverage Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: echo "This repository has been cloned to the runner"

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.0.0"
          channel: "stable"
      - run: echo "Using the latest stable version of flutter from subosito"

      - name: Get pub dependencies
        run: flutter pub get

      - name: Flutter analyze
        run: flutter analyze

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Add Coverde to project
        run: dart pub global activate coverde

      - name: Check test coverage
        run: coverde check 80

  create-build:
    name: Create ${{ matrix.target }} build
    needs: code-analysis-and-testing-with-coverage-analysis
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target: [Android, Ios]
        include:
          - target: Android
            build_target: apk --release
            os: ubuntu-latest
            tag: v1.0.${{github.run_number}}
            artifacts: "build/app/outputs/apk/release/*"
          - target: Ios
            build_target: ios --no-codesign
            os: macos-latest
            tag: ios.1.0.${{github.run_number}}
            artifacts: "build/ios/iphoneos/app.ipa"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: echo "This repository has been cloned to the runner"

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.0.0"
          channel: "stable"

      - name: Build for ${{ matrix.target }} platform
        run: flutter build ${{ matrix.build_target }}

      - if: matrix.target == 'Ios'
        name: Zip ipa
        run: |
          cd build/ios/iphoneos          
          mkdir Payload                  
          cd Payload                     
          ln -s ../Runner.app            
          cd ..                           
          zip -r app.ipa Payload

      - name: Create Releases for ${{ matrix.target }}
        uses: ncipollo/release-action@v1
        with:
          name: "News App ${{ matrix.target }} ${{ matrix.tag }}"
          artifacts: ${{ matrix.artifacts }}
          tag: ${{ matrix.tag }}
          body: "Release body sample for ${{ matrix.target }}"
          token: ${{ secrets.TOKEN }}

      - if: matrix.target =='Android'
        name: Send android apk via mail
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: mail.quantumgroupgh.com

          # Required mail server port:
          server_port: 465

          # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}

          # Required mail subject:
          subject: Apk Build for News App Android Release ${{ matrix.tag }}

          # Required recipients' addresses:
          to: eashitey@quantumgroupgh.com

          # Required sender full name (address can be skipped):
          from:
            Emmanuel Ashitey # <aamarh17@gmail.com>
            # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional plain body:
          html_body: |
            Build job of ${{ github.repository }} completed successfully!<br>

          # Optional carbon copy recipients:
          cc: dpartey@quantumgroupgh.com
          # Optional attachments:
          attachments: build/app/outputs/apk/release/app-release.apk
