name: Flutter CI/CD

# This workflow is triggered on pushes to the repository
on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  code-analysis-and-testing-with-coverage-analysis:
    name: Code Analysis and Testing With Coverage Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: echo "This repository has been cloned to the runner"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: echo "Using the latest stable version of flutter from subosito"

      # - name: Clean build
      #   run: flutter clean

      - name: Get pub dependencies
        run: flutter pub get

      - name: Flutter analyze
        run: flutter analyze

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Add Coverde to project
        run: dart pub global activate coverde

      - name: Check test coverage
        run: coverde check 80
      # - name: Very Good Coverage
      #   uses: VeryGoodOpenSource/very_good_coverage@v1.2.1
      #   with:
      #     min_coverage: 80

  build_android:
    name: Build Flutter (Android)
    needs: [code-analysis-and-testing-with-coverage-analysis] # requires the code-analysis-and-testing-with-coverage-analysis to run before the steps run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # - name: Get pub dependencies
      #   run: flutter pub get

      # - name: Flutter clean
      #   run: flutter clean

      - name: Flutter build android
        run: flutter build apk --release

  build_ios:
    name: Build Flutter (iOS)
    needs: [code-analysis-and-testing-with-coverage-analysis] # requires the code-analysis-and-testing-with-coverage-analysis to run before the steps run
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # - name: Get pub dependencies
      #   run: flutter pub get

      # - name: Flutter clean
      #   run: flutter clean

      - name: Flutter build ios
        run: flutter build ios --no-codesign
